### ISSUE TITLE
LLongestGap and RLongestGap - can they be the same class with direction parameter in constructor?

### ISSUE THREAD

**Issue by vladimirkovacevic** [LazarManic/GI-projekat#3]

**Comment by TamaraSretkovic** [comment]
I really love the idea of separate classes for each algorithm, but suggestion is in place. Created LongestGap parent class to contain the algo core, and LLongestGap and RLongestGap are now only creating LongestGap with direction parameter :) Let us know, if this approach is ok, I will leave the issue open.

**Comment by vladimirkovacevic** [comment]
Have you tested it to get 100% identical results?

**Comment by TamaraSretkovic** [comment]
Off course :) We have good test coverage, and all are passing as expected.
